version: 1.0-{build}
image:
- Visual Studio 2017
configuration:
- Debug
- Release
clone_depth: 1
environment:
  QT_VER: 5.13.2
  matrix:
  - CLIENT_TYPE: Internal
  - CLIENT_TYPE: External
install:
- ps: |
    If ($Env:CLIENT_TYPE -eq "External") {
      $Env:PLASMA_EXTERNAL_RELEASE = "ON"
    }

    if (!(Test-Path -PathType Container build)) {
        Write-Host "Creating build folder... " -noNewLine
        New-Item -ItemType directory build | Out-Null
        Write-Host "OK" -foregroundColor Green
    }

    $path = (Get-Location).Path
    Set-Location build

    Write-Host "Installing Python modules... " -noNewLine
    C:\Python27\python.exe -m pip install -r ../requirements.txt 2> $null
    Write-Host "OK" -foregroundColor Green

    Write-Host "Installing Python modules... " -noNewLine
    C:\Python27\python.exe -m pip install -r ../requirements.txt 2> $null
    Write-Host "OK" -foregroundColor Green

    Write-Host "Installing library dependencies... "
    Set-Location C:\Tools\vcpkg
    git pull 2> $null
    bootstrap-vcpkg.bat
    vcpkg upgrade --no-dry-run
    vcpkg install curl[sspi] expat freetype libjpeg-turbo libogg libpng libtheora libvorbis libvpx openal-soft `
                  opus pcre physx speex string-theory zlib --triplet x86-windows-static-md
    vcpkg integrate install
    Write-Host "OK" -foregroundColor Green

    Set-Location $path
    refreshenv
cache: C:\tools\vcpkg\installed
before_build:
- ps: |
    Set-Location build

    cmake -Wno-dev -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static-md `
    -DCMAKE_BUILD_TYPE=$Env:CONFIGURATION -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin -DQt5_DIR=C:\Qt\$Env:QT_VER\msvc2017\lib\cmake\Qt5 `
    -DPLASMA_EXTERNAL_RELEASE="$Env:PLASMA_EXTERNAL_RELEASE" -DPLASMA_BUILD_TESTS=ON -DPLASMA_BUILD_TOOLS=ON -DPLASMA_BUILD_RESOURCE_DAT=ON ..
build:
  project: build/Plasma.sln
  parallel: true
  verbosity: quiet
before_package:
- ps: |
    if ((Test-Path -PathType Container bin\$Env:CONFIGURATION)) {
      Set-Location bin\$Env:CONFIGURATION
      Get-ChildItem -File *.exe | Foreach {& "C:\Qt\$Env:QT_VER\msvc2017\bin\windeployqt.exe" --verbose 0 $_.fullname 2> $null}
      ls
    }
test: off
