name: Linux-CI
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    name: ${{ matrix.platform.str }}-${{ matrix.cfg.str }}
    strategy:
      matrix:
        platform:
          - { str: linux-x64 }
        cfg:
          #- { external: OFF, type: RelWithDebInfo, str: internal-release }
          - { external: OFF, type: Debug, str: internal-debug }
          #- { external: ON, type: RelWithDebInfo, str: external-release }

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              autoconf \
              cmake \
              libsecret-1-dev \
              libtool \
              nasm \
              ninja-build \
              qtbase5-dev

      - name: Configure
        run: |
          cmake \
            -DUSE_VCPKG=ON \
            -DCMAKE_BUILD_TYPE=${{ matrix.cfg.type }} \
            -DPLASMA_BUILD_TESTS=ON \
            -DPLASMA_BUILD_TOOLS=ON \
            -DPLASMA_EXTERNAL_RELEASE=${{ matrix.cfg.external }} \
            -DPLASMA_VCPKG_NUGET_SOURCE="https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            -DPLASMA_VCPKG_NUGET_OWNER="${{ github.repository_owner }}" \
            -DPLASMA_VCPKG_NUGET_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -DPLASMA_VCPKG_NUGET_RW=TRUE \
            -S . -B build

      - name: Build
        run: |
          cmake --build build -j 2

      - name: Test
        run: |
          cmake --build build --target check -j 2

      - name: Install
        run: |
          cmake --build build --target install -j 2
